window.APP_CONFIG = {
  supportedLangs: ['en', 'ru', 'sr'],
  // Local test: http://127.0.0.1:8787/api/analyze
  // Production: replace with the public HTTPS backend URL.
  analysisApi: 'http://127.0.0.1:8787/api/analyze',
  footerLinks: {
    site: 'https://nikolaysemenov.ru',
    github: 'https://github.com/ksider/nikolaysemenov.ru/tree/main/ftir',
    coffee: 'https://coindrop.to/nikolaysemenov',
  },
  chart: {
    defaultXRange: { min: 500, max: 4000 },
    zones: [
      { label: 'X–H heteroatoms', start: 4000, end: 2500, color: '#fb923c' },
      { label: 'C–H', start: 3100, end: 2800, color: '#fde047', text: '#111827' },
      { label: 'C≡C / C≡N', start: 2300, end: 2100, color: '#86efac', text: '#065f46' },
      { label: 'C=O', start: 1850, end: 1650, color: '#fb923c' },
      { label: 'C=C', start: 1650, end: 1500, color: '#86efac', text: '#065f46' },
      { label: 'halogenated', start: 1400, end: 1000, color: '#86efac', text: '#065f46' },
      { label: 'ethers', start: 1300, end: 1100, color: '#38bdf8', text: '#0b213b' },
      { label: 'organometallic', start: 1100, end: 700, color: '#fde047', text: '#111827' },
    ],
  },
  translations: {
    en: {
      title: 'FTIR TXT → CSV',
      description: 'Select multiple .txt files (FTIR spectra), set file name, merge to CSV, save a copy, and view the chart.',
      filesLabel: 'Files (.txt):',
      sampleIndex: 'Sample index (optional):',
      fileName: 'Output file name (.csv):',
      mergeBtn: 'Merge',
      appendFiles: 'Add files',
      chartSettings: 'Chart settings',
      xRange: 'X range (reverse):',
      yRange: 'Y range:',
      offsetsLabel: 'Y offsets per curve:',
      refresh: 'Refresh chart',
      saveCsv: 'Save CSV',
      resetZoom: 'Reset zoom',
      baselineSection: 'Baseline fit',
      baselineSeriesLabel: 'Series',
      baselineDegree: 'Degree',
      baselinePreview: 'Preview',
      baselineApply: 'Apply',
      baselineRevert: 'Revert',
      peaksTitle: 'Peaks / stripes',
      addStripe: 'Add stripe',
      copyStripes: 'Copy table',
      exportSession: 'Export session',
      importSession: 'Import session',
      copyPng: 'Copy chart PNG',
      copySvg: 'Copy chart SVG',
      peaksEmpty: 'No stripes yet. Set a marker and add it here.',
      tipPlaceholder: 'Tip database: coming soon',
      colWave: 'Wavenumber',
      colLabel: 'Label',
      colTip: 'Tip',
      peakHint: 'Click the chart to place a marker, then add it here.',
      peakHelpEyebrow: 'Peak search',
      peakHelpTitle: 'Peak detector guide',
      peakHelpIntro: 'These settings affect how automatic peaks are selected for the active spectrum.',
      detectorBaseline: 'Baseline',
      detectorBaselineEyebrow: 'Peak processing',
      detectorBaselineTitle: 'Baseline correction',
      detectorBaselineIntro: 'Choose how the slow background is removed from the active spectrum. Applying it is optional; without it, peaks are searched on the smoothed raw signal.',
      detectorBaselineNote: 'The main chart will switch to the corrected curve in the original display scale. Peak search will use the same applied correction.',
      detectorNotApplied: 'not applied',
      detectorRawMode: 'raw mode',
      detectorApplying: 'Applying baseline...',
      detectorPreviewing: 'Updating preview...',
      detectorApplied: 'Baseline applied to the active spectrum.',
      detectorReady: 'Ready for peak search',
      detectorApplyFirst: 'Apply a baseline correction before searching peaks.',
      detectorUnavailable: 'Baseline processing unavailable.',
      cancel: 'Cancel',
      applyBaseline: 'Apply baseline',
      peakProcessingEyebrow: 'Peak processing',
      peakProcessingTitle: 'Signal, baseline and corrected signal',
      peakProcessingSignal: 'Signal',
      peakProcessingBaseline: 'Baseline',
      peakProcessingCorrected: 'Corrected signal',
      peakProcessingBroad: 'Broad-band pass',
      peakProcessingHint: 'The red line is the baseline used by the fine detector. The green curve is searched for peaks. The broad-pass detector keeps broad bands separately.',
      peakProcessingEmpty: 'Run peak detection to view processing diagnostics.',
      peakHelpBaseline: 'Baseline method',
      peakHelpBaselineText: 'Removes slow background curvature before peak search. arPLS is the default. For very broad bands, compare the corrected curve and try Linear or None if the band is being removed.',
      peakHelpSignalType: 'Signal type',
      peakHelpSignalTypeText: 'Transmittance (%T) is converted to absorbance, so absorption bands are detected as peaks. For absorbance or intensity, the values are used directly.',
      peakHelpProminence: 'Prominence',
      peakHelpProminenceText: 'Minimum contrast against the local baseline. Increase it to remove noise and weak shoulders; decrease it to find weaker bands.',
      peakHelpDistance: 'Distance',
      peakHelpDistanceText: 'Minimum separation between peaks in cm⁻¹. Increase it when one broad band is split into many nearby peaks.',
      peakHelpSmooth: 'Smooth',
      peakHelpSmoothText: 'Moving-average window in data points. Increase it for noisy spectra, but a large value can flatten narrow peaks. Use an odd number.',
      peakHelpQuick: 'Quick start: try Prominence 0.02, Distance 8, Smooth 5, then adjust one setting at a time.',
      statusNoFiles: 'Add at least one file.',
      statusReading: 'Reading files...',
      statusSending: 'Merging...',
      statusReadyToSave: 'Merged. Use Save CSV to export visible series.',
      statusSaved: (p) => `Saved: ${p}`,
      statusNoDataCols: 'No data columns found (only wavenumber?)',
      statusNoNumeric: 'No numeric data to plot.',
      statusNoVisible: 'Select at least one series to save.',
      language: 'Language:',
      yAuto: 'auto',
    },
    ru: {
      title: 'FTIR TXT → CSV',
      description: 'Выберите несколько .txt файлов (спектры ФТИР), задайте имя, объедините, сохраните копию и смотрите график.',
      filesLabel: 'Файлы (.txt):',
      sampleIndex: 'Индекс образца (опционально):',
      fileName: 'Имя итогового файла (.csv):',
      mergeBtn: 'Объединить',
      appendFiles: 'Добавить файлы',
      chartSettings: 'Настройки диаграммы',
      xRange: 'Диапазон X (реверс):',
      yRange: 'Диапазон Y:',
      offsetsLabel: 'Смещения по Y для кривых:',
      refresh: 'Обновить график',
      saveCsv: 'Сохранить CSV',
      resetZoom: 'Сбросить зум',
      baselineSection: 'Базовая линия',
      baselineSeriesLabel: 'Серия',
      baselineDegree: 'Степень',
      baselinePreview: 'Предпросмотр',
      baselineApply: 'Применить',
      baselineRevert: 'Сбросить',
      peaksTitle: 'Пики / полосы',
      addStripe: 'Добавить полосу',
      copyStripes: 'Скопировать таблицу',
      exportSession: 'Экспорт сессии',
      importSession: 'Импорт сессии',
      copyPng: 'Скопировать PNG',
      copySvg: 'Скопировать SVG',
      peaksEmpty: 'Пока нет полос. Поставьте маркер и добавьте его сюда.',
      tipPlaceholder: 'Подсказки из базы появятся здесь',
      colWave: 'Волновое число',
      colLabel: 'Метка',
      colTip: 'Подсказка',
      peakHint: 'Кликните по графику, чтобы поставить маркер, затем добавьте его сюда.',
      peakHelpEyebrow: 'Поиск пиков',
      peakHelpTitle: 'Справка по детектору пиков',
      peakHelpIntro: 'Эти настройки влияют на автоматический поиск пиков в активном спектре.',
      detectorBaseline: 'Базовая линия',
      detectorBaselineEyebrow: 'Обработка пиков',
      detectorBaselineTitle: 'Коррекция базовой линии',
      detectorBaselineIntro: 'Выберите способ удаления медленного фона активного спектра. Применение необязательно: без него пики ищутся на сглаженном исходном сигнале.',
      detectorBaselineNote: 'На диаграмме появится скорректированная кривая в исходном масштабе. Поиск пиков будет использовать ту же применённую коррекцию.',
      detectorNotApplied: 'не применена',
      detectorRawMode: 'режим без baseline',
      detectorApplying: 'Применение baseline…',
      detectorPreviewing: 'Обновление предпросмотра…',
      detectorApplied: 'Baseline применена к активному спектру.',
      detectorReady: 'Готово к поиску пиков',
      detectorApplyFirst: 'Сначала примените коррекцию baseline.',
      detectorUnavailable: 'Не удалось обработать baseline.',
      cancel: 'Отмена',
      applyBaseline: 'Применить baseline',
      peakProcessingEyebrow: 'Обработка пиков',
      peakProcessingTitle: 'Сигнал, базовая линия и скорректированный сигнал',
      peakProcessingSignal: 'Сигнал',
      peakProcessingBaseline: 'Базовая линия',
      peakProcessingCorrected: 'Скорректированный сигнал',
      peakProcessingBroad: 'Проход широких полос',
      peakProcessingHint: 'Красная линия — базовая линия для основного детектора. По зелёной кривой ищутся пики. Для широких полос используется отдельный сохраняющий проход.',
      peakProcessingEmpty: 'Запустите поиск пиков, чтобы увидеть диагностику обработки.',
      peakHelpBaseline: 'Метод базовой линии',
      peakHelpBaselineText: 'Убирает медленную кривизну фона перед поиском пиков. По умолчанию используется arPLS. Для очень широких полос сравните скорректированную кривую и попробуйте Linear или None, если полоса исчезает.',
      peakHelpSignalType: 'Тип сигнала',
      peakHelpSignalTypeText: 'Пропускание (%T) преобразуется в поглощение, поэтому полосы поглощения ищутся как пики. Для absorbance или intensity значения используются напрямую.',
      peakHelpProminence: 'Prominence / выраженность',
      peakHelpProminenceText: 'Минимальный контраст относительно локальной базовой линии. Увеличьте, чтобы убрать шум и слабые плечи; уменьшите, чтобы находить слабые полосы.',
      peakHelpDistance: 'Distance / расстояние',
      peakHelpDistanceText: 'Минимальное расстояние между пиками в см⁻¹. Увеличьте, если одна широкая полоса разбивается на много соседних пиков.',
      peakHelpSmooth: 'Smooth / сглаживание',
      peakHelpSmoothText: 'Размер окна скользящего среднего в точках данных. Увеличьте для шумных спектров, но слишком большое окно может сгладить узкие пики. Используйте нечётное число.',
      peakHelpQuick: 'Быстрый старт: Prominence 0.02, Distance 8, Smooth 5. Затем меняйте только один параметр за раз.',
      statusNoFiles: 'Добавьте хотя бы один файл.',
      statusReading: 'Чтение файлов...',
      statusSending: 'Объединение...',
      statusReadyToSave: 'Объединено. Нажмите «Сохранить CSV» для видимых кривых.',
      statusSaved: (p) => `Сохранено: ${p}`,
      statusNoDataCols: 'Не удалось найти столбцы данных (только wavenumber?)',
      statusNoNumeric: 'Нет числовых данных для построения графика.',
      statusNoVisible: 'Отметьте хотя бы одну кривую для сохранения.',
      language: 'Язык:',
      yAuto: 'auto',
    },
    sr: {
      title: 'FTIR TXT → CSV',
      description: 'Izaberite više .txt fajlova (FTIR spektri), unesite ime, spojite u CSV, sačuvajte kopiju i pogledajte graf.',
      filesLabel: 'Fajlovi (.txt):',
      sampleIndex: 'Indeks uzorka (opciono):',
      fileName: 'Naziv izlaznog fajla (.csv):',
      mergeBtn: 'Spoji',
      appendFiles: 'Dodaj fajlove',
      chartSettings: 'Podešavanja grafa',
      xRange: 'Opseg X (obrnuto):',
      yRange: 'Opseg Y:',
      offsetsLabel: 'Pomeraj po Y za krive:',
      refresh: 'Osveži graf',
      saveCsv: 'Sačuvaj CSV',
      resetZoom: 'Resetuj zum',
      baselineSection: 'Baseline fit',
      baselineSeriesLabel: 'Serija',
      baselineDegree: 'Stepen',
      baselinePreview: 'Pregled',
      baselineApply: 'Primeni',
      baselineRevert: 'Poništi',
      peaksTitle: 'Vrhovi / trake',
      addStripe: 'Dodaj traku',
      copyStripes: 'Kopiraj tabelu',
      exportSession: 'Izvezi sesiju',
      importSession: 'Uvezi sesiju',
      copyPng: 'Kopiraj PNG',
      copySvg: 'Kopiraj SVG',
      peaksEmpty: 'Još nema traka. Postavi marker i dodaj ga ovde.',
      tipPlaceholder: 'Saveti iz baze uskoro',
      colWave: 'Talasni broj',
      colLabel: 'Oznaka',
      colTip: 'Savet',
      peakHint: 'Klik na graf postavlja marker, pa ga dodaj ovde.',
      peakHelpEyebrow: 'Pretraga vrhova',
      peakHelpTitle: 'Vodič za detektor vrhova',
      peakHelpIntro: 'Ova podešavanja utiču na automatski izbor vrhova u aktivnom spektru.',
      detectorBaseline: 'Bazna linija',
      detectorBaselineEyebrow: 'Obrada vrhova',
      detectorBaselineTitle: 'Korekcija bazne linije',
      detectorBaselineIntro: 'Izaberite način uklanjanja sporog pozadinskog signala aktivnog spektra. Primena je opciona; bez nje se vrhovi traže na zaglađenom sirovom signalu.',
      detectorBaselineNote: 'Graf će prikazati korigovanu krivu u originalnoj skali. Pretraga vrhova koristiće istu primenjenu korekciju.',
      detectorNotApplied: 'nije primenjena',
      detectorRawMode: 'bez bazne linije',
      detectorApplying: 'Primena bazne linije…',
      detectorPreviewing: 'Ažuriranje pregleda…',
      detectorApplied: 'Bazna linija je primenjena na aktivni spektar.',
      detectorReady: 'Spremno za pretragu vrhova',
      detectorApplyFirst: 'Prvo primenite korekciju bazne linije.',
      detectorUnavailable: 'Obrada bazne linije nije uspela.',
      cancel: 'Otkaži',
      applyBaseline: 'Primeni baznu liniju',
      peakProcessingEyebrow: 'Obrada vrhova',
      peakProcessingTitle: 'Signal, bazna linija i korigovani signal',
      peakProcessingSignal: 'Signal',
      peakProcessingBaseline: 'Bazna linija',
      peakProcessingCorrected: 'Korigovani signal',
      peakProcessingBroad: 'Prolaz za široke trake',
      peakProcessingHint: 'Crvena linija je bazna linija glavnog detektora. Zelena kriva se koristi za traženje vrhova. Široke trake se čuvaju posebnim prolazom.',
      peakProcessingEmpty: 'Pokrenite detekciju vrhova da biste videli dijagnostiku obrade.',
      peakHelpBaseline: 'Metod bazne linije',
      peakHelpBaselineText: 'Uklanja sporu zakrivljenost pozadine pre traženja vrhova. arPLS je podrazumevan. Za veoma široke trake proverite korigovanu krivu i probajte Linear ili None ako traka nestaje.',
      peakHelpSignalType: 'Tip signala',
      peakHelpSignalTypeText: 'Transmisija (%T) se pretvara u apsorbancu, pa se apsorpcione trake traže kao vrhovi. Kod absorbance ili intensity vrednosti se koriste direktno.',
      peakHelpProminence: 'Prominence / izraženost',
      peakHelpProminenceText: 'Minimalni kontrast u odnosu na lokalnu baznu liniju. Povećajte da uklonite šum i slaba ramena; smanjite da pronađete slabije trake.',
      peakHelpDistance: 'Distance / rastojanje',
      peakHelpDistanceText: 'Minimalno rastojanje između vrhova u cm⁻¹. Povećajte kada se jedna široka traka deli na mnogo susednih vrhova.',
      peakHelpSmooth: 'Smooth / zaglađivanje',
      peakHelpSmoothText: 'Veličina prozora pokretnog proseka u tačkama podataka. Povećajte za bučne spektre, ali veliko okno može izravnati uske vrhove. Koristite neparan broj.',
      peakHelpQuick: 'Brzi početak: Prominence 0.02, Distance 8, Smooth 5. Zatim menjajte samo jedan parametar odjednom.',
      statusNoFiles: 'Dodajte bar jedan fajl.',
      statusReading: 'Čitanje fajlova...',
      statusSending: 'Spajanje...',
      statusReadyToSave: 'Spojeno. Klikni „Sačuvaj CSV” za vidljive krive.',
      statusSaved: (p) => `Sačuvano: ${p}`,
      statusNoDataCols: 'Nema kolona sa podacima (samo wavenumber?)',
      statusNoNumeric: 'Nema numeričkih podataka za graf.',
      statusNoVisible: 'Izaberi bar jednu krivu za čuvanje.',
      language: 'Jezik:',
      yAuto: 'auto',
    },
  },
};
